# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(188, 181)
        self.center_label = QtWidgets.QLabel(Form)
        self.center_label.setGeometry(QtCore.QRect(55, 50, 81, 81))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(45)
        self.center_label.setFont(font)
        self.center_label.setObjectName("center_label")
        self.add_label = QtWidgets.QPushButton(Form)
        self.add_label.setGeometry(QtCore.QRect(10, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.add_label.setFont(font)
        self.add_label.setStyleSheet("background:rgba(0,0,0,0);color: #FFFFFF;")
        self.add_label.setObjectName("add_label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 140, 31, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:rgba(0,0,0,0);color: #FFFFFF;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.add_label.clicked.connect(Form.push_button_add_click)
        self.pushButton.clicked.connect(Form.push_button_clear_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.center_label.setText(_translate("Form", "🥛"))
        self.add_label.setText(_translate("Form", "✚"))
        self.pushButton.setText(_translate("Form", "〇"))
