# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(182, 328)
        self.drink_table_view = QtWidgets.QTableView(Form)
        self.drink_table_view.setGeometry(QtCore.QRect(10, 30, 161, 291))
        self.drink_table_view.setObjectName("drink_table_view")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
